name: Node CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commit count
        env:
          PR_COMMIT_COUNT: ${{ github.event.pull_request.commits }}
        run: |
          echo 'FETCH_DEPTH=$($(env.PR_COMMIT_COUNT) + 1)' >> $GITHUB_ENV
          echo "${{ env.FETCH_DEPTH }} $FETCH_DEPTH"

      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
          #fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: get file list
        run: |
          mkdir ~/tmp/
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} --name-only --relative '*src/**/*.ts' > ~/tmp/changed_files

      - name: lint
        run: npx eslint $(cat ~/tmp/changed_files)

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
        #with:
          #ref: ${{ github.event.pull_request.head.sha }}

      - name: Git Diff
        run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # - name: check type
      #   run: npm run checktype

      - name: lint
        run: npm run lint

      - name: build release
        run: npm run release

      - name: Test generated DTS
        run: npm run test:dts

      - name: Unit Test
        run: npm run test
