name: Source Release

on:
  workflow_dispatch:

jobs:
  validate-source:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v4

      - name: Build source release
        run: |
          npm ci
          npx jest --version
          npm run release
          npm run test
          npm run test:dts
